export const PERMISSION_LIST = {
  UPDATE_AUTH_USER_ROLE: 'UPDATE_AUTH_USER_ROLE',
  CREATE_AUTH_ROLE: 'CREATE_AUTH_ROLE',
  UPDATE_AUTH_ROLE: 'UPDATE_AUTH_ROLE',
  DELETE_AUTH_ROLE: 'DELETE_AUTH_ROLE',
  GET_AUTH_ROLE: 'GET_AUTH_ROLE',

  CREATE_FEATURE: 'CREATE_FEATURE',
  UPDATE_FEATURE: 'UPDATE_FEATURE',
  DELETE_FEATURE: 'DELETE_FEATURE',
  GET_FEATURE: 'GET_FEATURE',

  CREATE_EXCHANGE: 'CREATE_EXCHANGE',
  UPDATE_EXCHANGE: 'UPDATE_EXCHANGE',
  DELETE_EXCHANGE: 'DELETE_EXCHANGE',
  GET_EXCHANGE: 'GET_EXCHANGE',

  CREATE_GENERAL_SETTING: 'CREATE_GENERAL_SETTING',
  UPDATE_GENERAL_SETTING: 'UPDATE_GENERAL_SETTING',
  DELETE_GENERAL_SETTING: 'DELETE_GENERAL_SETTING',
  GET_GENERAL_SETTING: 'GET_GENERAL_SETTING',

  CREATE_RESOLUTION: 'CREATE_RESOLUTION',
  UPDATE_RESOLUTION: 'UPDATE_RESOLUTION',
  DELETE_RESOLUTION: 'DELETE_RESOLUTION',
  GET_RESOLUTION: 'GET_RESOLUTION',

  CREATE_SYMBOL: 'CREATE_SYMBOL',
  UPDATE_SYMBOL: 'UPDATE_SYMBOL',
  DELETE_SYMBOL: 'DELETE_SYMBOL',
  GET_SYMBOL: 'GET_SYMBOL',

  GET_USER: 'GET_USER',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',

  GET_ADMIN: 'GET_ADMIN',
  CREATE_ADMIN: 'CREATE_ADMIN',
  UPDATE_ADMIN: 'UPDATE_ADMIN',

  GET_ROLE: 'GET_ROLE',
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',

  CREATE_SYMBOL_SETTING_ROLE: 'CREATE_SYMBOL_SETTING_ROLE',
  UPDATE_SYMBOL_SETTING_ROLE: 'UPDATE_SYMBOL_SETTING_ROLE',
  DELETE_SYMBOL_SETTING_ROLE: 'DELETE_SYMBOL_SETTING_ROLE',

  ON_OFF_REGISTER: 'ON_OFF_REGISTER',

  GET_TRANSACTION: 'GET_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  REQUEST_INTERVENTION: 'REQUEST_INTERVENTION',

  GET_BOT_SETTING: 'GET_BOT_SETTING',
  CREATE_BOT_SETTING: 'CREATE_BOT_SETTING',
  UPDATE_BOT_SETTING: 'UPDATE_BOT_SETTING',
  DELETE_BOT_SETTING: 'DELETE_BOT_SETTING',

  GET_PACKAGE: 'GET_PACKAGE',
  CREATE_PACKAGE: 'CREATE_PACKAGE',
  UPDATE_PACKAGE: 'UPDATE_PACKAGE',
  DELETE_PACKAGE: 'DELETE_PACKAGE',

  GET_CURRENCY: 'GET_CURRENCY',
  CREATE_CURRENCY: 'CREATE_CURRENCY',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  DELETE_CURRENCY: 'DELETE_CURRENCY',

  EXPORT_USER: 'EXPORT_USER',
  EXPORT_TRANSACTION: 'EXPORT_TRANSACTION',

  GET_BOT: 'GET_BOT',
  CREATE_BOT: 'CREATE_BOT',
  UPDATE_BOT: 'UPDATE_BOT',
  DELETE_BOT: 'DELETE_BOT',

  GET_SYSTEM_TRADE_HISTORY: 'GET_SYSTEM_TRADE_HISTORY',

  GET_BOT_TRADING: 'GET_BOT_TRADING',
  CREATE_BOT_TRADING: 'CREATE_BOT_TRADING',
  UPDATE_BOT_TRADING: 'UPDATE_BOT_TRADING',
  DELETE_BOT_TRADING: 'DELETE_BOT_TRADING',
};
