import {
  SvgFibo,
  SvgTrendLine,
  SvgPath,
  SvgText,
  SvgTriangle,
  SvgRectangle,
  SvgVerticalLine,
  SvgHorizontalRay,
  SvgHorizontalLine,
  SvgArrowMarker,
  SvgExtendedLine,
  SvgCallout,
  SvgArrow,
  SvgLongPosition,
  SvgShortPosition,
} from '@/assets/images/svg';

export const DRAW_TOOLS = {
  trend_line: {
    type: 'trend_line',
    name: 'Trend Line',
    stateName: 'trendLines',
    featureId: 'DRAW_TREND_LINE',
    icon: <SvgTrendLine />,
  },
  arrow: {
    type: 'arrow',
    name: 'Arrow',
    stateName: 'arrows',
    featureId: 'DRAW_ARROW',
    icon: <SvgArrow />,
  },
  horizontal_ray: {
    type: 'horizontal_ray',
    name: 'Horizontal Ray',
    stateName: 'horizontalRays',
    featureId: 'DRAW_HORIZONTAL_RAY',
    icon: <SvgHorizontalRay />,
  },
  horizontal_line: {
    type: 'horizontal_line',
    name: 'Horizontal Line',
    stateName: 'horizontalLines',
    featureId: 'DRAW_HORIZONTAL_LINE',
    icon: <SvgHorizontalLine />,
  },
  vertical_line: {
    type: 'vertical_line',
    name: 'Vertical Line',
    stateName: 'verticalLines',
    featureId: 'DRAW_VERTICAL_LINE',
    icon: <SvgVerticalLine />,
  },
  extended_line: {
    type: 'extended_line',
    name: 'Extended Line',
    stateName: 'extendedLines',
    featureId: 'DRAW_EXTENDED_LINE',
    icon: <SvgExtendedLine />,
  },
  fibonacci_retracement: {
    type: 'fibonacci_retracement',
    name: 'Fibo retracement',
    stateName: 'retracements',
    featureId: 'DRAW_FIBONACCI_RETRACEMENT',
    icon: <SvgFibo />,
  },
  long_position: {
    type: 'long_position',
    name: 'Long Position',
    stateName: 'longPositions',
    featureId: 'DRAW_LONG_POSITION',
    icon: <SvgLongPosition />,
  },
  short_position: {
    type: 'short_position',
    name: 'Short Position',
    stateName: 'shortPositions',
    featureId: 'DRAW_SHORT_POSITION',
    icon: <SvgShortPosition />,
  },
  path: {
    type: 'path',
    name: 'Path',
    stateName: 'paths',
    hide: false,
    featureId: 'DRAW_PATH',
    icon: <SvgPath />,
  },
  rectangle: {
    type: 'rectangle',
    name: 'Rectangle',
    stateName: 'rectangles',
    featureId: 'DRAW_RETANGLE',
    icon: <SvgRectangle />,
  },
  triangle: {
    type: 'triangle',
    name: 'Triangle',
    stateName: 'triangles',
    featureId: 'DRAW_TRIANGLE',
    icon: <SvgTriangle />,
  },
  text: {
    type: 'text',
    name: 'Text',
    stateName: 'texts',
    hide: false,
    featureId: 'DRAW_TEXT',
    icon: <SvgText />,
  },
  callout: {
    type: 'callout',
    name: 'Callout',
    stateName: 'callouts',
    hide: false,
    featureId: 'DRAW_CALLOUT',
    icon: <SvgCallout />,
  },
  arrow_marker: {
    type: 'arrow_marker',
    name: 'Arrow Marker',
    stateName: 'arrowMarkers',
    featureId: 'DRAW_ARROW_MARKER',
    icon: <SvgArrowMarker />,
  },
};
