export const FEATURE_ID = {
  PAGE_HOME: 'PAGE_HOME',
  PAGE_PROFILE: 'PAGE_PROFILE',
  PAGE_CHART: 'PAGE_CHART',
  PAGE_SIGNAL_BOT_DASHBOARD: 'PAGE_SIGNAL_BOT_DASHBOARD',
  PAGE_TRADING_BOT_DASHBOARD: 'PAGE_TRADING_BOT_DASHBOARD',
  PAGE_PRICING: 'PAGE_PRICING',

  BOT_SIGNAL: 'BOT_SIGNAL',
  BOT_TRADING: 'BOT_TRADING',

  BUTTON_DASHBOARD: 'BUTTON_DASHBOARD',
  BUTTON_DASHBOARD_CEXTRADING: 'BUTTON_DASHBOARD_CEXTRADING',
  BUTTON_DASHBOARD_SIGNAL_BOT: 'BUTTON_DASHBOARD_SIGNAL_BOT',
  BUTTON_DASHBOARD_TRADING_BOT: 'BUTTON_DASHBOARD_TRADING_BOT',
  BUTTON_USER_GUIDE: 'BUTTON_USER_GUIDE',

  SIDEBAR_COINMAP_SESSION: 'SIDEBAR_COINMAP_SESSION',
  HEADER_LOGO: 'HEADER_LOGO',
  FOOTER_LOGO: 'FOOTER_LOGO',
  FOOTER_COPYRIGHT: 'FOOTER_COPYRIGHT',
  MODAL_POLICY: 'MODAL_POLICY',
  MEDIA_FACEBOOK: 'MEDIA_FACEBOOK',
  MEDIA_TWITTER: 'MEDIA_TWITTER',
  MEDIA_TELEGRAM: 'MEDIA_TELEGRAM',
  MEDIA_YOUTUBE: 'MEDIA_YOUTUBE',
  MEDIA_DISCORD: 'MEDIA_DISCORD',
  SUPPORT_EMAIL: 'SUPPORT_EMAIL',
};
