import { utcToZonedTime } from 'date-fns-tz';
import { defaultFormatters } from '@/utils/format';
import { timeFormat } from 'd3-time-format';

const formater = timeFormat(defaultFormatters.secondFormat);
export const formatDateUtc = (dateUtc, timezone) => {
  return formater(utcToZonedTime(dateUtc, timezone));
};

export const TIME_ZONE_LIST = [
  {
    label: '(UTC-10)',
    labelTable: '(UTC-10) Honolulu',
    value: '-10',
    timezone: 'Pacific/Honolulu',
  },
  {
    label: '(UTC-9)',
    labelTable: '(UTC-9) Juneau',
    value: '-9',
    timezone: 'America/Juneau',
  },
  {
    label: '(UTC-8)',
    labelTable: '(UTC-8) Los Angeles',
    value: '-8',
    timezone: 'America/Los_Angeles',
  },
  {
    label: '(UTC-8)',
    labelTable: '(UTC-8) Vancouver',
    value: '-8',
    timezone: 'America/Vancouver',
  },
  {
    label: '(UTC-7)',
    labelTable: '(UTC-7) Denver',
    value: '-7',
    timezone: 'America/Denver',
  },
  {
    label: '(UTC-7)',
    labelTable: '(UTC-7) Phoenix',
    value: '-7',
    timezone: 'America/Phoenix',
  },
  {
    label: '(UTC-6)',
    labelTable: '(UTC-6) Chicago',
    value: '-6',
    timezone: 'America/Chicago',
  },
  {
    label: '(UTC-6)',
    labelTable: '(UTC-6) Mexico City',
    value: '-6',
    timezone: 'America/Mexico_City',
  },
  {
    label: '(UTC-6)',
    labelTable: '(UTC-6) San Salvador',
    value: '-6',
  },
  {
    label: '(UTC-5)',
    labelTable: '(UTC-5) Bogota',
    value: '-5',
    timezone: 'America/Bogota',
  },
  {
    label: '(UTC-5)',
    labelTable: '(UTC-5) Lima',
    value: '-5',
    timezone: 'America/Lima',
  },
  {
    label: '(UTC-5)',
    labelTable: '(UTC-5) New York',
    value: '-5',
    timezone: 'America/New_York',
  },
  {
    label: '(UTC-5)',
    labelTable: '(UTC-5) Toronto',
    value: '-5',
    timezone: 'America/Toronto',
  },
  {
    label: '(UTC-4)',
    labelTable: '(UTC-4) Caracas',
    value: '-4',
    timezone: 'America/Caracas',
  },
  {
    label: '(UTC-3)',
    labelTable: '(UTC-3) Buenos Aires',
    value: '-3',
    timezone: 'America/Argentina/Buenos_Aires',
  },
  {
    label: '(UTC-3)',
    labelTable: '(UTC-3) Santiago',
    value: '-3',
    timezone: 'America/Santiago',
  },
  {
    label: '(UTC-3)',
    labelTable: '(UTC-3) Sao Paulo',
    value: '-3',
    timezone: 'America/Sao_Paulo',
  },
  {
    label: '(UTC)',
    labelTable: '(UTC) Dublin',
    value: '0',
    timezone: 'Europe/Dublin',
  },
  {
    label: '(UTC)',
    labelTable: '(UTC) Lisbon',
    value: '0',
    timezone: 'Europe/Lisbon',
  },
  {
    label: '(UTC)',
    labelTable: '(UTC) London',
    value: '0',
    timezone: 'Europe/London',
  },
  {
    label: '(UTC)',
    labelTable: '(UTC) Reykjavik',
    value: '0',
    timezone: 'Atlantic/Reykjavik',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Amsterdam',
    value: '+1',
    timezone: 'Europe/Amsterdam',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Belgrade',
    value: '+1',
    timezone: 'Europe/Belgrade',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Berlin',
    value: '+1',
    timezone: 'Europe/Berlin',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Bratislava',
    value: '+1',
    timezone: 'Europe/Bratislava',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Brussels',
    value: '+1',
    timezone: 'Europe/Brussels',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Budapest',
    value: '+1',
    timezone: 'Europe/Budapest',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Copenhagen',
    value: '+1',
    timezone: 'Europe/Copenhagen',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Lagos',
    value: '+1',
    timezone: 'Africa/Lagos',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Luxembourg',
    value: '+1',
    timezone: 'Europe/Luxembourg',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Madrid',
    value: '+1',
    timezone: 'Europe/Madrid',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Malta',
    value: '+1',
    timezone: 'Europe/Malta',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Oslo',
    value: '+1',
    timezone: 'Europe/Oslo',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Paris',
    value: '+1',
    timezone: 'Europe/Paris',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Rome',
    value: '+1',
    timezone: 'Europe/Rome',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Stockholm',
    value: '+1',
    timezone: 'Europe/Stockholm',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Tunis',
    value: '+1',
    timezone: 'Africa/Tunis',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Warsaw',
    value: '+1',
    timezone: 'Europe/Warsaw',
  },
  {
    label: '(UTC+1)',
    labelTable: '(UTC+1) Zurich',
    value: '+1',
    timezone: 'Europe/Zurich',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Athens',
    value: '+2',
    timezone: 'Europe/Athens',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Bucharest',
    value: '+2',
    timezone: 'Europe/Bucharest',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Cairo',
    value: '+2',
    timezone: 'Africa/Cairo',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Helsinki',
    value: '+2',
    timezone: 'Europe/Helsinki',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Jerusalem',
    value: '+2',
    timezone: 'Asia/Jerusalem',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Johannesburg',
    value: '+2',
    timezone: 'Africa/Johannesburg',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Riga',
    value: '+2',
    timezone: 'Europe/Riga',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Tallinn',
    value: '+2',
    timezone: 'Europe/Tallinn',
  },
  {
    label: '(UTC+2)',
    labelTable: '(UTC+2) Vilnius',
    value: '+2',
    timezone: 'Europe/Vilnius',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Bahrain',
    value: '+3',
    timezone: 'Asia/Bahrain',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Istanbul',
    value: '+3',
    timezone: 'Europe/Istanbul',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Kuwait',
    value: '+3',
    timezone: 'Asia/Kuwait',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Moscow',
    value: '+3',
    timezone: 'Europe/Moscow',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Nairobi',
    value: '+3',
    timezone: 'Africa/Nairobi',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Qatar',
    value: '+3',
    timezone: 'Asia/Qatar',
  },
  {
    label: '(UTC+3)',
    labelTable: '(UTC+3) Riyadh',
    value: '+3',
    timezone: 'Asia/Riyadh',
  },
  {
    label: '(UTC+3:30)',
    labelTable: '(UTC+3:30) Tehran',
    value: '+3:30',
    timezone: 'Asia/Tehran',
  },
  {
    label: '(UTC+4)',
    labelTable: '(UTC+4) Dubai',
    value: '+4',
    timezone: 'Asia/Dubai',
  },
  {
    label: '(UTC+4)',
    labelTable: '(UTC+4) Muscat',
    value: '+4',
    timezone: 'Asia/Muscat',
  },
  {
    label: '(UTC+5)',
    labelTable: '(UTC+5) Ashgabat',
    value: '+5',
    timezone: 'Asia/Ashgabat',
  },
  {
    label: '(UTC+5)',
    labelTable: '(UTC+5) Karachi',
    value: '+5',
    timezone: 'Asia/Karachi',
  },
  {
    label: '(UTC+5:30)',
    labelTable: '(UTC+5:30) Kolkata',
    value: '+5:30',
    timezone: 'Asia/Kolkata',
  },
  {
    label: '(UTC+5:45)',
    labelTable: '(UTC+5:45) Kathmandu',
    value: '+5:45',
    timezone: 'Asia/Kathmandu',
  },
  {
    label: '(UTC+6)',
    labelTable: '(UTC+6) Almaty',
    value: '+6',
    timezone: 'Asia/Almaty',
  },
  {
    label: '(UTC+7)',
    labelTable: '(UTC+7) Bangkok',
    value: '+7',
    timezone: 'Asia/Bangkok',
  },
  {
    label: '(UTC+7)',
    labelTable: '(UTC+7) Ho Chi Minh',
    value: '+7',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    label: '(UTC+7)',
    labelTable: '(UTC+7) Jakarta',
    value: '+7',
    timezone: 'Asia/Jakarta',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Chongqing',
    value: '+8',
    timezone: 'Asia/Macau',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Hong Kong',
    value: '+8',
    timezone: 'Asia/Hong_Kong',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Manila',
    value: '+8',
    timezone: 'Asia/Manila',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Perth',
    value: '+8',
    timezone: 'Australia/Perth',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Shanghai',
    value: '+8',
    timezone: 'Asia/Shanghai',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Singapore',
    value: '+8',
    timezone: 'Asia/Singapore',
  },
  {
    label: '(UTC+8)',
    labelTable: '(UTC+8) Taipei',
    value: '+8',
    timezone: 'Asia/Taipei',
  },
  {
    label: '(UTC+9)',
    labelTable: '(UTC+9) Seoul',
    value: '+9',
    timezone: 'Asia/Seoul',
  },
  {
    label: '(UTC+9)',
    labelTable: '(UTC+9) Tokyo',
    value: '+9',
    timezone: 'Asia/Tokyo',
  },
  {
    label: '(UTC+10)',
    labelTable: '(UTC+10) Brisbane',
    value: '+10',
    timezone: 'Australia/Brisbane',
  },
  {
    label: '(UTC+10:30)',
    labelTable: '(UTC+10:30) Adelaide',
    value: '+10:30',
    timezone: 'Australia/Adelaide',
  },
  {
    label: '(UTC+11)',
    labelTable: '(UTC+11) Sydney',
    value: '+11',
    timezone: 'Australia/Sydney',
  },
  {
    label: '(UTC+12)',
    labelTable: '(UTC+12) Norfolk Island',
    value: '+12',
    timezone: 'Pacific/Norfolk',
  },
  {
    label: '(UTC+13)',
    labelTable: '(UTC+13) New Zealand',
    value: '+13',
    timezone: 'Pacific/Auckland',
  },
  {
    label: '(UTC+13)',
    labelTable: '(UTC+13) Tokelau',
    value: '+13',
    timezone: 'Pacific/Auckland',
  },
  {
    label: '(UTC+13:45)',
    labelTable: '(UTC+13:45) Chatham Islands',
    value: '+13:45',
    timezone: 'Pacific/Chatham',
  },
];
