export const FETCH_LASTUPDATEID_ORDERBOOK_SYMBOL_BINANCE =
  'FETCH_LASTUPDATEID_ORDERBOOK_SYMBOL_BINANCE';
export const FETCH_DEPTH_ORDERBOOK_SYMBOL_BINANCE =
  'FETCH_DEPTH_ORDERBOOK_SYMBOL_BINANCE';
export const FETCH_CANDLESTICK_SYMBOL_BINANCE =
  'FETCH_CANDLESTICK_SYMBOL_BINANCE';
export const FETCH_TRAHISTORY_SYMBOL_BINANCE =
  'FETCH_TRAHISTORY_SYMBOL_BINANCE';

export const SET_THEME = 'SETTING_THEME_SET_THEME';
export const SET_CHART_SESSION = 'SETTING_SET_CHART_SESSION';

export const ADD_ERROR = 'ADD_ERROR';
export const DEL_ERROR = 'DEL_ERROR';
export const LOADING = 'LOADING';
export const SET_SHOW_NEED_UPGRADE_PLAN = 'SET_SHOW_NEED_UPGRADE_PLAN';
export const SET_DEACTIVATE = 'SET_DEACTIVATE';
export const SET_WARNING_CLOSE_CHART = 'SET_WARNING_CLOSE_CHART';
export const SET_MERCHANT_INFO = 'SET_MERCHANT_INFO';

export const ADD_CHART = 'ADD_CHART';
export const UPDATE_CHART = 'UPDATE_CHART';
export const DELETE_CHART = 'DELETE_CHART';
export const UPDATE_CHART_SYMBOL = 'UPDATE_CHART_SYMBOL';
export const UPDATE_CHART_INTERVAL = 'UPDATE_CHART_INTERVAL';

export const UPDATE_CHART_DATA = 'UPDATE_CHART_DATA';
export const REPLACE_CHART_DATA = 'REPLACE_CHART_DATA';
export const APPEND_CHART_DATA = 'APPEND_CHART_DATA';
export const REPLACE_LAST_CANDLE = 'REPLACE_LAST_CANDLE';
export const UPDATE_CHART_ORDERFLOW = 'UPDATE_CHART_ORDERFLOW';
export const UPDATE_CHART_ACCUMULATED_DELTA = 'UPDATE_CHART_ACCUMULATED_DELTA';

export const UPDATE_LIST_PAIRS = 'UPDATE_LIST_PAIRS';
export const SET_RESOLUTION_LIST = 'SET_RESOLUTION_LIST';

export const UPDATE_SYMBOL_SEARCH_CHART_ID = 'UPDATE_SYMBOL_SEARCH_CHART_ID';
export const SET_SYMBOL_FILTER = 'SET_SYMBOL_FILTER';
export const SET_CHART_SETTINGS = 'SET_CHART_SETTINGS';
export const SET_FOOTPRINT_SETTINGS = 'SET_FOOTPRINT_SETTINGS';
export const SET_VIEW_SETTINGS = 'SET_VIEW_SETTINGS';
export const SET_STATUS_LINE_SETTINGS = 'SET_STATUS_LINE_SETTINGS';
export const SET_TIME_SCALE_SETTINGS = 'SET_TIME_SCALE_SETTINGS';
export const SET_PRICE_SCALE_SETTINGS = 'SET_PRICE_SCALE_SETTINGS';
export const SET_CHART_THEME = 'SET_CHART_THEME';
export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_SELECTED_CHART = 'SET_SELECTED_CHART';
export const LAYER_TOGGLE = 'LAYER_TOGGLE';
export const LAYER_ADD = 'LAYER_ADD';
export const LAYER_DEL = 'LAYER_DEL';
export const LAYER_MOVE = 'LAYER_MOVE';
export const LAYER_UPDATE = 'LAYER_UPDATE';
export const LAYER_LIST_TOGGLE = 'LAYER_LIST_TOGGLE';
export const TOOGLE_ADD_LAYER_MODAL = 'TOOGLE_ADD_LAYER_MODAL';
export const SET_CHARTS_FROM_SERVER = 'SET_CHARTS_FROM_SERVER';
export const UPDATE_WATCH_LIST_FROM_SERVER = 'UPDATE_WATCH_LIST_FROM_SERVER';

export const SAVE_SETTINGS_TO_LOCAL = 'SAVE_SETTINGS_TO_LOCAL';
export const RESTORE_SETTING_FROM_LOCAL = 'RESTORE_SETTING_FROM_LOCAL';

export const DRAW_START = 'DRAW_START';
export const DRAW_UPDATE = 'DRAW_UPDATE';
export const DRAW_END = 'DRAW_END';
export const DRAW_SELECT = 'DRAW_SELECT';
export const DRAW_DELETE = 'DRAW_DELETE';
export const SET_DRAW_SETTING = 'SET_DRAW_SETTING';

export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';

export const TOGGLE_MODAL_JUMP_TO = 'TOGGLE_MODAL_JUMP_TO';
export const TOGGLE_MODAL_EXPORT = 'TOGGLE_MODAL_EXPORT';

export const BOT_SIGNALS_PANE_TOGGLE = 'BOT_SIGNALS_PANE_TOGGLE';
export const BOT_SIGNALS_UPDATE_DATA = 'BOT_SIGNALS_UPDATE_DATA';
export const LAYER_SETTING = 'LAYER_SETTING';
export const SET_LAYER_ID_SETTING = 'SET_LAYER_ID_SETTING';
export const SET_LAYER_SETTING = 'SET_LAYER_SETTING';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_USER_INFO = 'SET_USER_INFO';
