export enum ADDITIONAL_DATA_TYPE {
  FAQ = 'FAQ',
  PKG_PERIOD = 'PKG_PERIOD',
  TBOT_PERIOD = 'TBOT_PERIOD',
  SBOT_PERIOD = 'SBOT_PERIOD',
  TBOT_FEE = 'TBOT_FEE',
  HOME_PAGE = 'HOME_PAGE',
  POLICY = 'POLICY',
}

export enum APP_SETTING_NAME {
  BROKER_SETTING = 'BROKER_SETTING',
}
